-- Migration number: 0001 	 2026-09-14T10:23:08.307Z
PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE IF NOT EXISTS "skins"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
  "uuid" TEXT UNIQUE NOT NULL, "url" TEXT);
CREATE TABLE IF NOT EXISTS "player_data"(
  "id" INTEGER PRIMARY KEY UNIQUE NOT NULL,
  "uuid" TEXT UNIQUE NOT NULL,
  "username" TEXT NOT NULL,
  "isOnline" INTEGER NOT NULL,
  "firstSeen" TEXT NOT NULL,
  "lastSeen" TEXT NOT NULL
, "isPrivate" INTEGER NOT NULL DEFAULT '1');
CREATE TABLE IF NOT EXISTS "loadouts"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
);
CREATE TABLE IF NOT EXISTS "statistics"(
  "id" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL,
  "uuid" TEXT UNIQUE NOT NULL,
  "advancements" INTEGER NOT NULL DEFAULT '0',
  "blocksMined" INTEGER NOT NULL DEFAULT '0',
  "blocksPlaced" INTEGER NOT NULL DEFAULT '0',
  "damageAbsorbed" INTEGER NOT NULL DEFAULT '0',
  "damageDealt" INTEGER NOT NULL DEFAULT '0',
  "damageTaken" INTEGER NOT NULL DEFAULT '0',
  "damageResisted" INTEGER NOT NULL DEFAULT '0',
  "distanceTraveled" INTEGER NOT NULL DEFAULT '0',
  "deaths" INTEGER NOT NULL DEFAULT '0',
  "level" INTEGER NOT NULL DEFAULT '0',
  "mobsKilled" INTEGER NOT NULL DEFAULT '0',
  "playersKilled" INTEGER NOT NULL DEFAULT '0',
  "playTime" INTEGER NOT NULL DEFAULT '0',
  "timeSinceLastDeath" INTEGER NOT NULL DEFAULT '0'
);
DELETE FROM sqlite_sequence;
