name: Build Tailwind CSS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git credentials for pushing
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - name: Build TailwindCSS
        run: npx tailwindcss -i ./src/input.css -o ./src/output.css --minify

      - name: Commit output.css
        run: |
          git add src/output.css
          git commit -m "Build: output.css from GitHub Actions" || echo "No changes to commit"
          git push
