name: Build Tailwind CSS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npx tailwindcss -i ./src/input.css -o ./src/output.css --minify

      - name: Commit and push output.css
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output.css
          git commit -m "Build output.css" || echo "No changes to commit"
          git push
